
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:email itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:mobile itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mobile>

<field:text itemname="内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:text>

<field:addtime itemname="留言时间" autofield="1" type="datetime" isnull="true" default=""  maxlength="250" page="">
</field:addtime>
