<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	
<field:jiage itemname="价格" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:jiage>
<field:yanse itemname="颜色" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default="红色,白色,黑色"  maxlength="250" page="">
</field:yanse>

<field:chuliqi itemname="处理器" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:chuliqi>

<field:neicun itemname="内存" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:neicun>
