
<field:realname itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:realname>

<field:email itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:mobile itemname="手机号" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mobile>

<field:text itemname="内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:text>
